const state={issues:[],days:[]};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fmt=v=>new Date(v).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"});
function params(){return{q:document.querySelector("#search").value.trim().toLowerCase(),status:document.querySelector("#status").value,category:document.querySelector("#category").value,day:document.querySelector("#day").value};}
function render(){
 const p=params(); let list=state.issues;
 if(p.day) list=list.filter(i=>i.snapshot_date===p.day);
 list=list.filter(i=>(!p.q||[i.title,i.summary,i.category,i.authority].join(" ").toLowerCase().includes(p.q))&&(!p.status||i.status===p.status)&&(!p.category||i.category===p.category));
 document.querySelector("#count").textContent=list.length+" shown";
 document.querySelector("#issues").innerHTML=list.map((i,idx)=>`<a class="card" href="issue.html?id=${encodeURIComponent(i.id)}"><div class="rank">#${idx+1} · ${esc(i.category)} · ${esc(i.snapshot_date||"")}</div><h3>${esc(i.title)}</h3><p>${esc(i.summary)}</p><div class="meta"><span class="pill">${esc(i.status)}</span><span class="pill">Score ${esc(i.score)}</span><span class="pill">${i.sources?.length||0} sources</span><span class="pill">Updated ${esc(fmt(i.last_updated))}</span></div></a>`).join("")||"<p>No issues found for this day.</p>";
}
async function init(){
 const data=await fetch("data/issues.json",{cache:"no-store"}).then(r=>r.json());
 const archive=await fetch("data/days.json",{cache:"no-store"}).then(r=>r.json()).catch(()=>({days:[]}));
 state.issues=data.issues||[]; state.days=archive.days||[];
 document.querySelector("#last-updated").textContent="Latest data: "+fmt(data.generated_at);
 const day=document.querySelector("#day");
 state.days.forEach(d=>day.insertAdjacentHTML("beforeend",`<option value="${esc(d.date)}">${esc(d.label)} · ${d.count} issues</option>`));
 ["#search","#status","#category","#day"].forEach(s=>document.querySelector(s).addEventListener("input",render));
 const statuses=[...new Set(state.issues.map(x=>x.status).filter(Boolean))],cats=[...new Set(state.issues.map(x=>x.category).filter(Boolean))];
 statuses.forEach(x=>document.querySelector("#status").insertAdjacentHTML("beforeend",`<option>${esc(x)}</option>`));
 cats.forEach(x=>document.querySelector("#category").insertAdjacentHTML("beforeend",`<option>${esc(x)}</option>`));
 render();
}
init().catch(e=>{document.querySelector("#issues").innerHTML="<p>Data is being generated by the free daily pipeline. Please refresh after the first run.</p>";console.error(e)});